---
version: '3'
services:
  mysql:
    container_name: my-rails5-template-mysql
    image: mysql:8.0.11
    volumes:
      - ./docker/etc/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/vol/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
