FROM node:9.9.0 as node
FROM ruby:2.5.1

WORKDIR /workspace

COPY --from=node /usr/local/bin/node /usr/local/bin/
# /usr/local/bin/yarn is wrapped by shell script
COPY --from=node /opt/yarn* /opt/yarn
RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarnpkg
RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn

ENV LANG C.UTF-8

EXPOSE 3000
